FROM node:21

COPY ./postman /postman
COPY ./run-postman.sh /postman

# Installa Newman, il runner di Postman
RUN npm install -g newman
RUN npm install -g newman-reporter-htmlextra

# Cancella il file precedente se esiste
RUN rm -f /postman/Integration_tests_Console_Service2.postman_collection.json
# Cancella il file precedente se esiste
RUN rm -f /postman/Integration_tests_Console_Service.postman_collection.json

# Copia il nuovo file
COPY ./postman/Integration_tests_Console_Service2.postman_collection.json /postman

RUN chmod 777 /postman/run-postman.sh \
  && chown -R 1001 /postman/run-postman.sh \
  && chmod -R "g+rwX" /postman/run-postman.sh \
  && chown -R 1001:root /postman/run-postman.sh
# Comando per eseguire la collection Postman
USER 1001
CMD ["/bin/bash","-c","./postman/run-postman.sh"]
